### ISSUE TITLE
trying to read props of undefined

### ISSUE THREAD

**Issue by CombustibleToast** [CombustibleToast/CAROLINE#9]
just need to add ? after pauseonnextplay
```
Song started normally; collected timestamp 1693754902421                                                                Options:                                                                                                                {                                                                                                                         filter: 'audioonly',                                                                                                    fmt: 'mp3',                                                                                                             highWaterMark: 1073741824,                                                                                              liveBuffer: 20000,                                                                                                      dlChunkSize: 4096,                                                                                                      bitrate: 128,                                                                                                           quality: 'lowestaudio'                                                                                                }           
MUSIC - [INFO] [Loudspeaker] Musical Modron: idle -> buffering
MUSIC - [INFO] [Loudspeaker] Musical Modron: buffering -> playing
/home/pi/bots/CAROLINE/lib/musicFunctions/connectLoudspeaker.js:72
                if (loudspeakerClient.player.pauseOnNextPlay) {
                                             ^

TypeError: Cannot read properties of undefined (reading 'pauseOnNextPlay')
    at AudioPlayer.<anonymous> (/home/pi/bots/CAROLINE/lib/musicFunctions/connectLoudspeaker.js:72:32)
    at AudioPlayer.emit (node:events:513:28)
    at set state [as state] (/home/pi/bots/CAROLINE/node_modules/@discordjs/voice/dist/index.js:1083:12)
    at OggDemuxer.onReadableCallback (/home/pi/bots/CAROLINE/node_modules/@discordjs/voice/dist/index.js:1135:22)
    at Object.onceWrapper (node:events:627:28)
    at OggDemuxer.emit (node:events:525:35)
    at emitReadable_ (node:internal/streams/readable:590:12)
    at process.processTicksAndRejections (node:internal/process/task_queues:81:21)

Node.js v18.12.1
```

**Comment by CombustibleToast** [comment]
wait no `player` is undefined wtf
